Fatal error: exception Failure("return gives num expected void in 42")
